# Generated by Django 3.1.3 on 2020-11-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='todocategory',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='todocategory',
            name='todo_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.DeleteModel(
            name='TodoCategory',
        ),
    ]
